### ISSUE TITLE
use of undeclared crate or module `exif` when using png feature only

### ISSUE THREAD

**Issue by hillin** [etemesi254/zune-image#164]
Cargo.toml:

```toml
[dependencies]
zune-image = { version = "0.4.15", default-features = false, features = [
    "png",
] }
```

Build error:
```
zune-image-0.4.15\src\codecs\png.rs:13:5
   |
13 | use exif::experimental::Writer;
   |     ^^^^ use of undeclared crate or module `exif`       

error[E0282]: type annotations needed for `std::io::Cursor<Vec<_>>`
```

Enabling all default features can solve this problem.
